source:
    git_url: ../

package:
    name: circletest
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}

    script: python setup.py install

requirements:
    build:
        - python
        - pbr

    run:
        - python

